### ISSUE TITLE
Unexpected 'c'

### ISSUE THREAD

**Issue by EaterSteam** [np6hd/discordIntegration#1]
When i run the code it pops up with an error for the config.json file "Unexpected token c in JSON at position 0"
Any idea why??

**Comment by np6hd** [comment]
Note: the .gitignore file in the repo, it doesnt include the config.json

**Comment by EaterSteam** [comment]
also is there a way to use cracked accounts ?

**Comment by np6hd** [comment]
Per your deleted comment: That is beyond the scope of this project and further discussion in that matter is not viable.
